### ISSUE TITLE
Error Scanning sites

### ISSUE THREAD

**Issue by darkmatter1505** [WebBreacher/tilde_enum#34]
I have been getting this error with the last couple of sites I have tried to scan. 

Traceback (most recent call last):
  File "../../Tools/tilde_enum-master/tilde_enum.py", line 669, in <module>
    if __name__ == "__main__": main()
  File "../../Tools/tilde_enum-master/tilde_enum.py", line 512, in main
    findings = checkEightDotThreeEnum(url.scheme + '://' + url.netloc, check_string, url.path)
  File "../../Tools/tilde_enum-master/tilde_enum.py", line 314, in checkEightDotThreeEnum
    fileOrDir(files, url, stub)
  File "../../Tools/tilde_enum-master/tilde_enum.py", line 245, in fileOrDir
    filename = findExtension(url, stub)
  File "../../Tools/tilde_enum-master/tilde_enum.py", line 203, in findExtension
    if resp1a.code == 404:  # Got the first valid char
AttributeError: 'int' object has no attribute 'code'

**Comment by WebBreacher** [comment]
Can you please provide:

1. the version of OS you are running this from
1. the version of Python you are using.
1. the full command line that you are running when you get this (with all the switches and flags)
1. Also if the server you are testing has a URL that you can share that'd be helpful. I won't hack it....I promise. You can DM me with it if you'd prefer.

This script was written in python 2.x. If you are using 3.x then you may see these errors. I'll look into it further too.

**Comment by WebBreacher** [comment]
Hi. Just wondering if this is still an issue and, if so, can you paste some additional details? Maybe re-run the script with the -v flag and paste that output into this issue?
