### ISSUE TITLE
AttributeError: 'URLError' object has no attribute 'read'

### ISSUE THREAD

**Issue by PierrePDP** [WebBreacher/tilde_enum#36]
So I am trying to scan a specific site, but every time I try to scan it I receive the following:

> Traceback (most recent call last):
  File "./tilde_enum.py", line 670, in <module>
    if __name__ == "__main__": main()
  File "./tilde_enum.py", line 484, in main
    response_code = initialCheckUrl(args.url)
  File "./tilde_enum.py", line 106, in initialCheckUrl
    not_there_response_content_length = len(not_there_response.read())
AttributeError: 'URLError' object has no attribute 'read'

Any idea what might possibly be causing it?

**Comment by WebBreacher** [comment]
Can you paste in sanitized command line for what you are running? Add the -v switch so we can see the output too. Any additional details you have about the system and python and if this was working before or just happened on a specific site will help.

**Comment by buddha4you** [comment]
I'm experiencing the same issue as the person above. I'm running the script in the Cygwin terminal (MobaXterm):

python tilde_enum.py -u http://test_url.com -d IIS.txt
[-]  Testing with dummy file request http://test_url.com/8oq4CsX9J9.htm
[-]    URLNotThere -> HTTP Code: 404, Response Length: 1245
[-]  Testing with user-submitted http://test_url.com
Traceback (most recent call last):
  File "tilde_enum.py", line 670, in <module>
    if __name__ == "__main__": main()
  File "tilde_enum.py", line 484, in main
    response_code = initialCheckUrl(args.url)
  File "tilde_enum.py", line 122, in initialCheckUrl
    if url_response.getcode():
AttributeError: 'URLError' object has no attribute 'getcode'

**Comment by WebBreacher** [comment]
I noticed you didn't enter a -w WORDLIST. The -d flag is optional but -w is not.

**Comment by PierrePDP** [comment]
> python ./tilde_enum.py -u https://url/ -w ./lowercase.txt -v
[-]  Entering "Verbose Mode"....brace yourself for additional information.
[-]  Testing with dummy file request https://url/agiZka8yBM.htm
Traceback (most recent call last):
  File "./tilde_enum.py", line 670, in <module>
    if __name__ == "__main__": main()
  File "./tilde_enum.py", line 484, in main
    response_code = initialCheckUrl(args.url)
  File "./tilde_enum.py", line 106, in initialCheckUrl
    not_there_response_content_length = len(not_there_response.read())
AttributeError: 'URLError' object has no attribute 'read'

That's the error I am getting, with the verbose flag on. Can't specify the URL directly as it is under a NDA.

**Comment by buddha4you** [comment]
I just tried with -w but got the same error messages. The command was the following:
➤ python tilde_enum.py -u http://test_url.com/ -v -w IIS.txt
[-]  Entering "Verbose Mode"....brace yourself for additional information.
[-]  Testing with dummy file request http://test_url.com/IYp7NUTWgc.htm
[-]    URLNotThere -> HTTP Code: 404, Response Length: 1245
[-]  Testing with user-submitted http://test_url.com/
Traceback (most recent call last):
  File "tilde_enum.py", line 670, in <module>
    if __name__ == "__main__": main()
  File "tilde_enum.py", line 484, in main
    response_code = initialCheckUrl(args.url)
  File "tilde_enum.py", line 122, in initialCheckUrl
    if url_response.getcode():
AttributeError: 'URLError' object has no attribute 'getcode'

**Comment by WebBreacher** [comment]
Thank you both for submitting the verbose content. MUCH Appreciated. I can see that it is happening with different word lists and HTTP and HTTPS. So that is helpful. I'll need to work on this and cannot do it during my "day job". Stay tuned.

**Comment by H5a337230** [comment]
I am waiting for your response WebBreacher

`Traceback (most recent call last):
  File "tilde_enum.py", line 670, in <module>
    if __name__ == "__main__": main()
  File "tilde_enum.py", line 484, in main
    response_code = initialCheckUrl(args.url)
  File "tilde_enum.py", line 106, in initialCheckUrl
    not_there_response_content_length = len(not_there_response.read())
AttributeError: 'URLError' object has no attribute 'read'`

I used https + -w + -d
without -d again it shows above message

**Comment by WebBreacher** [comment]
Hey everyone. I realize that you are waiting for me to make a fix for this however, at this time, I have many other priorities and cannot give this the troubleshooting attention it needs. 

The wonderful nature of open source (free) tools such as this one is that we all can try to fix the bugs and issues, not just the original creator. I don't and will not have time to work on this in the near future but if you do, let me know what solutions you find and submit a PR (pull request) to get your fixes into the project.

**Comment by H5a337230** [comment]
I found something

`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "tilde_enum.py", line 672, in <module>
    if __name__ == "__main__": main()
  File "tilde_enum.py", line 486, in main
    response_code = initialCheckUrl(args.url)
  File "tilde_enum.py", line 108, in initialCheckUrl
    not_there_response_content_length = len(not_there_response.read())
AttributeError: 'URLError' object has no attribute 'read'
`

I think it because of SSL certificate

**Comment by H5a337230** [comment]
FIXED

**Comment by WebBreacher** [comment]
Merged and THANKS! 

Everyone else, see if this fixes your issues. If so, post here and I'll close issue.
