### ISSUE TITLE
AttributeError: 'URLError' object has no attribute 'code'

### ISSUE THREAD

**Issue by darkmatter1505** [WebBreacher/tilde_enum#39]
Running the following command I get the error below. I have tried multiple wordlists and get the same results.

./tilde_enum.py -u https://iis -w /usr/share/dirb/wordlists/vulns/iis.txt 
[-]  Testing with dummy file request https://iis/cl3qBgsLMr.htm
[-]    URLNotThere -> HTTP Code: 404, Response Length: 5199
[-]  Testing with user-submitted https://iis
[-]    URLUser -> HTTP Code: 200, Response Length: 0
[+]  The server is reporting that it is IIS (Microsoft-IIS/7.5).
[+]  The server is vulnerable to the tilde enumeration vulnerability (IIS/5|6.x)..
[+]  Found file:  ac_run . js
[+]  Found a directory: afrore
[+]  Found a directory: alanfl
Traceback (most recent call last):
  File "./tilde_enum.py", line 672, in <module>
    if __name__ == "__main__": main()
  File "./tilde_enum.py", line 515, in main
    findings = checkEightDotThreeEnum(url.scheme + '://' + url.netloc, check_string, url.path)
  File "./tilde_enum.py", line 317, in checkEightDotThreeEnum
    fileOrDir(files, url, stub)
  File "./tilde_enum.py", line 252, in fileOrDir
    checkForDirectory(url+stub)
  File "./tilde_enum.py", line 241, in checkForDirectory
    if resp.code == 404:
**AttributeError: 'URLError' object has no attribute 'code'**

**Comment by WebBreacher** [comment]
Thanks for reporting the error. It looks identical to issue #36 . I must admit that I'm no longer maintaining this code. 

Are you using the latest version as the fix for #36 fixed others' issues. There may be another issues with HTTPS though.

**Comment by darkmatter1505** [comment]
Yes, I'm using the latest clone from github.

Dark Matter

________________________________
